version: '3'
services:
  capture_motion:
    build: .
    #ports:
    #- "5000:5000"
    volumes:
    #- .:/code
    #- logvolume01:/var/log
    - capture_motion/run_cmo.py run_cmo.py
    - capture_motion/COPY config_docker.json config.json
    - capture_motion/cmo.py cmo.py
    links:
    - redis
  redis:
    image: redis
volumes:
  logvolume01: {}